### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ORION9k** [jensb89/Netflix-to-Trakt-Import#11]
Hello,
While running I am encountering the following error

`Traceback (most recent call last):
  File "netflix2trakt.py", line 31, in <module>
    for row in csvReader:
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\csv.py", line 111, in __next__
    row = next(self.reader)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5486: character maps to <undefined>`

**Comment by jensb89** [comment]
Should be fixed by the commit from @HampusAndersson01.
