### ISSUE TITLE
datetime error

### ISSUE THREAD

**Issue by OlickQC** [jensb89/Netflix-to-Trakt-Import#4]
Hi,
Maybe its because im in Quebec Canada but I cant import my Netflix history on trakt.

The Python error:
```
Traceback (most recent call last):
  File "D:\Windows\Téléchargements\Netflix-to-Trakt-Import-master\netflix2trakt.py", line 163, in <module>
    time = datetime.datetime.strptime(watchedTime + ' 20:15', '%d.%m.%y %H:%M')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021.12.15 20:15' does not match format '%d.%m.%y %H:%M'
```
Do you have an idea why ?

My CSV is formatted like that:
```
Title,Date
"Tiger King: Tiger King 2: Beg Your Pardon","2021-12-15"
"Fate/EXTRA Last Encore: Oblitus Copernican Theory: Praeteritus Limbus Vorago","2021-12-15"
"House of Secrets: The Burari Deaths: Limited Series: 11 Bodies","2021-10-20"
"Squid Game: Season 1: One Lucky Day","2021-10-04"
"Squid Game: Season 1: Front Man","2021-10-04"
"Squid Game: Season 1: VIPS","2021-10-04"
"Squid Game: Season 1: Gganbu","2021-10-04"
"Squid Game: Season 1: A Fair World","2021-10-04"
"Squid Game: Season 1: Stick to the Team","2021-10-03"
"Squid Game: Season 1: The Man with the Umbrella","2021-10-03"
"Squid Game: Season 1: Hell","2021-10-03"
"Squid Game: Season 1: Red Light, Green Light","2021-10-03"
```

Thank you!

**Comment by jensb89** [comment]
I don't know why this is happening to you, but it seems the date format is in the wrong way, day and year is mixed.
For a quickfix can you try to change the following lines in "netflix2traktp.y"?:

`time = datetime.datetime.strptime(watchedTime + ' 20:15', '%d.%m.%y %H:%M')
`
to 

`time = datetime.datetime.strptime(watchedTime + ' 20:15', '%y.%m.%d %H:%M')
`

in line 163 and 184.

I will have a closer look at it another time. Maybe the Netflix date format has changed or it really is different in Canada ;)
If possible I will try to upload a fix for it as soon as I find some time. But the above should already help you :)

**Comment by jensb89** [comment]
Update:
I can confirm my CSV has a different style, so we need some config option to set the datetime format.
```
Title,Date
"Haus des Geldes: Teil 5: Eine Familientradition","04.12.21"
"Haus des Geldes: Teil 5: Bettgeflüster","04.12.21"
"Haus des Geldes: Teil 5: Die Theorie der Eleganz","03.12.21"
"Haus des Geldes: Teil 5: Wunschdenken","03.12.21"
"Haus des Geldes: Teil 5: Sicherheitsventil","03.12.21"
"Alice in Borderland: Staffel 1: Folge 8","30.11.21"
"Alice in Borderland: Staffel 1: Folge 7","30.11.21"
"Alice in Borderland: Staffel 1: Folge 6","30.11.21"
"Alice in Borderland: Staffel 1: Folge 5","29.11.21"
"Alice in Borderland: Staffel 1: Folge 4","29.11.21"
"Alice in Borderland: Staffel 1: Folge 3","28.11.21"
"Alice in Borderland: Staffel 1: Folge 2","28.11.21"
"Alice in Borderland: Staffel 1: Folge 1","28.11.21"

**Comment by jensb89** [comment]
I added a config option. Try "%Y-%m-%d" or "%Y.%m.%d". That should solve the problem.
